server:
  port: 8080

spring:
  application:
    name: book-App
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql : true
  datasource:
    url: jdbc:mysql://localhost:3306/book_ci_cd
    username: root
    password: Chanducra0@